# .github/workflows/deploy.yml

name: GitHub Actions CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Add permissions for the deploy job
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # - run: npm test # You can uncomment this if you have tests

      - name: Upload build artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          # This should be the directory where your build output is located
          path: ./dist

  # New job to handle the deployment to GitHub Pages
  deploy:
    # This job needs the build job to complete successfully
    needs: build
    
    # Only run this job on a push to the main branch
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
